---
- name: Deploy pip.conf
  copy:
    src: files/.pip
    dest: /root/

- name: install pexpect
  pip:
    name: pexpect

- name: Assure {{ workspace }} present
  file:
    path: "{{ workspace }}"
    state: directory
    mode: '0755'

- name: copy miniconda setup package
  copy:
    src: files/Miniconda3-latest-Linux-x86_64.sh
    dest: "{{ workspace }}"
    mode: '0755'

- name: if {{ miniconda_location }} already present
  command: test -d {{ miniconda_location }}
  register: test_miniconda_location

- name: End the play for hosts that miniconda already present
  meta: end_host
  when: test_miniconda_location.rc == 0

- name: install miniconda
  expect:
    chdir: "{{ workspace }}"
    command: ./Miniconda3-latest-Linux-x86_64.sh
    responses:
      'Please, press ENTER to continue.*>>> ': '' 
      '(.*)--More--(.*)': ' '
      'Do you accept the license terms\? \[yes\|no\](.*)\[no\] >>> ': 'yes'
      '\[/root/miniconda3\] >>> ': "{{ miniconda_location }}"
      'by running conda init\? \[yes\|no\](.*)\[no\] >>> ': 'yes'
    echo: yes
    notify: echo uptime