---
- name: copy conda environment definition file
  copy:
    src: files/e.py36.yml
    dest: "{{ workspace }}"

- name: create conda python3.6 env named e.py36
  command: "{{ miniconda_location }}/bin/conda env create -f {{ workspace }}/e.py36.yml"