---
- name: yum install packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gcc
      - dstat
      - htop
      - tree
      - rsync
      - expat-devel
      - mariadb-devel
      - mariadb-libs
  notify:
    - echo uptime
